//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHManager.Blazor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Questions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Questions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHManager.Blazor.Resources.Questions", typeof(Questions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mým cílem je redukce hmotnosti.
        /// </summary>
        public static string Q_1_1 {
            get {
                return ResourceManager.GetString("Q_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mým cílem je zdravě se stravovat.
        /// </summary>
        public static string Q_1_10 {
            get {
                return ResourceManager.GetString("Q_1_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mým cílem je zlepšit svou fyzickou kondici.
        /// </summary>
        public static string Q_1_11 {
            get {
                return ResourceManager.GetString("Q_1_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mým cílem je líbit se sám/sama sobě.
        /// </summary>
        public static string Q_1_12 {
            get {
                return ResourceManager.GetString("Q_1_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co mi ve splnění cíle nejvíce pomůže: (např. pomůže mi chystat si obědy doma).
        /// </summary>
        public static string Q_1_13 {
            get {
                return ResourceManager.GetString("Q_1_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co mi může splnění cíle zhatit: (např. sladkosti doma ve skříni).
        /// </summary>
        public static string Q_1_14 {
            get {
                return ResourceManager.GetString("Q_1_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co udělám jako první: (např. nakoupím si zdravé potraviny).
        /// </summary>
        public static string Q_1_15 {
            get {
                return ResourceManager.GetString("Q_1_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mým cílem je přibírání hmotnosti.
        /// </summary>
        public static string Q_1_2 {
            get {
                return ResourceManager.GetString("Q_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mým cílem je udržování hmotnosti (nechci ani redukovat, ani přibrat).
        /// </summary>
        public static string Q_1_3 {
            get {
                return ResourceManager.GetString("Q_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O kolik kg chcete zhubnout (přibrat)? [kg].
        /// </summary>
        public static string Q_1_4 {
            get {
                return ResourceManager.GetString("Q_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mým cílem je zhubnout hlavně rychle.
        /// </summary>
        public static string Q_1_5 {
            get {
                return ResourceManager.GetString("Q_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mým cílem je zhubnout pomaleji, ale zaměřit se na udržitelný výsledek.
        /// </summary>
        public static string Q_1_6 {
            get {
                return ResourceManager.GetString("Q_1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mým cílem je zbavit se problémů doprovázejících prediabetes nebo diabetes 2. typu.
        /// </summary>
        public static string Q_1_7 {
            get {
                return ResourceManager.GetString("Q_1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mým cílem je zbavit se problémů doprovázejících diabetes 1. typu.
        /// </summary>
        public static string Q_1_8 {
            get {
                return ResourceManager.GetString("Q_1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mým cílem je snížit množství užívaných léků.
        /// </summary>
        public static string Q_1_9 {
            get {
                return ResourceManager.GetString("Q_1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte diagnostikovanou cukrovku 1. typu?.
        /// </summary>
        public static string Q_2_1 {
            get {
                return ResourceManager.GetString("Q_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodělal/a jste některé z následujících onemocnění – mozková mrtvice, ischemická choroba srdeční (angina pectoris) nebo infarkt myokardu, ischemická choroba dolních končetin?.
        /// </summary>
        public static string Q_2_10 {
            get {
                return ResourceManager.GetString("Q_2_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodělal/a jste transplantaci a nyní užíváte imunosupresiva (léky na potlačení imunity)?.
        /// </summary>
        public static string Q_2_11 {
            get {
                return ResourceManager.GetString("Q_2_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodělal/a jste transplantaci ledvin?.
        /// </summary>
        public static string Q_2_12 {
            get {
                return ResourceManager.GetString("Q_2_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selhávají Vám ledviny?.
        /// </summary>
        public static string Q_2_13 {
            get {
                return ResourceManager.GetString("Q_2_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selhává Vám srdce?.
        /// </summary>
        public static string Q_2_14 {
            get {
                return ResourceManager.GetString("Q_2_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chodíte na dialýzu ledvin?.
        /// </summary>
        public static string Q_2_15 {
            get {
                return ResourceManager.GetString("Q_2_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proděláváte nebo jste prodělal/a onkologické onemocněnía jste nyní v remisi? (ukončená léčba, pravidelné kontroly).
        /// </summary>
        public static string Q_2_16 {
            get {
                return ResourceManager.GetString("Q_2_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měla jste někdy diagnostikované nádorové onemocnění prsu, vaječníku nebo vejcovodu?.
        /// </summary>
        public static string Q_2_17 {
            get {
                return ResourceManager.GetString("Q_2_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte diagnostikovanou dnu nebo zvýšenou hladinu kyseliny močové?.
        /// </summary>
        public static string Q_2_18 {
            get {
                return ResourceManager.GetString("Q_2_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V případě, že máte diagnostikovanou dnu nebo zvýšenou hladinu kyseliny močové, užíváte léky na její snížení?.
        /// </summary>
        public static string Q_2_19 {
            get {
                return ResourceManager.GetString("Q_2_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte diagnostikovaný prediabetes? (náběh na cukrovku).
        /// </summary>
        public static string Q_2_2 {
            get {
                return ResourceManager.GetString("Q_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte diagnostikované onemocnění štítné žlázy?.
        /// </summary>
        public static string Q_2_20 {
            get {
                return ResourceManager.GetString("Q_2_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte diagnostikovanou sníženou funkci štítné žlázy (hypofunkci)? (užíváte léky Letrox, Euthyrox).
        /// </summary>
        public static string Q_2_21 {
            get {
                return ResourceManager.GetString("Q_2_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud máte diagnostikované jiné onemocnění štítné žlázy, popište, o jaké onemocnění jde:.
        /// </summary>
        public static string Q_2_22 {
            get {
                return ResourceManager.GetString("Q_2_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte zvýšené jaterní testy?  (hodnoty jaterních enzymů ALT, AST, ALP a/nebo GGT).
        /// </summary>
        public static string Q_2_23 {
            get {
                return ResourceManager.GetString("Q_2_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trápí Vás žlučníkové problémy, nebo máte žlučník vyoperovaný? (akutní zánět žlučníku, žlučníkové kameny, vyoperovaný? (akutní zánět žlučníku, žlučníkové kameny, žlučová kolika).
        /// </summary>
        public static string Q_2_24 {
            get {
                return ResourceManager.GetString("Q_2_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užíváte léky na ředění krve? (například warfarin, anopyrin, godasal).
        /// </summary>
        public static string Q_2_25 {
            get {
                return ResourceManager.GetString("Q_2_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V případě, že užíváte léky na ředění krve, užíváte konkrétně warfarin?.
        /// </summary>
        public static string Q_2_26 {
            get {
                return ResourceManager.GetString("Q_2_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trpíte Crohnovou chorobou?.
        /// </summary>
        public static string Q_2_27 {
            get {
                return ResourceManager.GetString("Q_2_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trpíte ulcerózní kolitidou?.
        /// </summary>
        public static string Q_2_28 {
            get {
                return ResourceManager.GetString("Q_2_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trpíte bolestí kloubů?.
        /// </summary>
        public static string Q_2_29 {
            get {
                return ResourceManager.GetString("Q_2_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte zvýšenou hladinu krevního cukru? (nad 5,6 mmol/l).
        /// </summary>
        public static string Q_2_3 {
            get {
                return ResourceManager.GetString("Q_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte diagnostikovanou refluxní chorobu jícnu nebo trpíte pyrózou (pálením žáhy)?.
        /// </summary>
        public static string Q_2_30 {
            get {
                return ResourceManager.GetString("Q_2_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte nějaké kožní problémy?.
        /// </summary>
        public static string Q_2_31 {
            get {
                return ResourceManager.GetString("Q_2_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud máte jiné kožní problémy, prosím, popište je:.
        /// </summary>
        public static string Q_2_32 {
            get {
                return ResourceManager.GetString("Q_2_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užíváte nějaké léky?.
        /// </summary>
        public static string Q_2_33 {
            get {
                return ResourceManager.GetString("Q_2_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud užíváte jakékoliv léky, prosím, vypište jejich celý název, dávkování a dobu po kterou je užíváte:.
        /// </summary>
        public static string Q_2_34 {
            get {
                return ResourceManager.GetString("Q_2_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud užíváté léky, obsahuje některý z těchto léků účinnou látku methotrexát? (např. léky při nádorových onemocněních, psoriáze nebo revmatoidní artritidě,  např. Aldesta, Methotrexat, Metoject, Injexate, Nordimet, Trexan).
        /// </summary>
        public static string Q_2_35 {
            get {
                return ResourceManager.GetString("Q_2_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užíváte nějaké doplňky stravy?.
        /// </summary>
        public static string Q_2_36 {
            get {
                return ResourceManager.GetString("Q_2_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud užíváte jakékoliv doplňky stravy, prosím, vypište jejich celý název, dávkování a dobu po kterou je užíváte:.
        /// </summary>
        public static string Q_2_37 {
            get {
                return ResourceManager.GetString("Q_2_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte od lékaře doporučenou nějakou speciální dietu (například bezezbytková, nízkobílkovinová,...)?.
        /// </summary>
        public static string Q_2_38 {
            get {
                return ResourceManager.GetString("Q_2_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud máte od lékaře doporučenou dietu, napište, prosím, jakou dietu Vám lékař doporučil a v čem spočívá?.
        /// </summary>
        public static string Q_2_39 {
            get {
                return ResourceManager.GetString("Q_2_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte diagnostikovanou cukrovku 2. typu?.
        /// </summary>
        public static string Q_2_4 {
            get {
                return ResourceManager.GetString("Q_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud trpíte ještě i jinými onemocněními, která nebyla v dotazníku zmíněna, prosím, vypište je:.
        /// </summary>
        public static string Q_2_40 {
            get {
                return ResourceManager.GetString("Q_2_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud máte diagnostikovanou cukrovku 2. typu, jakým způsobem ji léčíte?.
        /// </summary>
        public static string Q_2_5 {
            get {
                return ResourceManager.GetString("Q_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berete léky na ovlivnění tuků v krvi? (statiny – např. léky na cholesterol, fibráty, jedná se např. Lipanthyl, Atoris, Rosucard, Ezetrol).
        /// </summary>
        public static string Q_2_6 {
            get {
                return ResourceManager.GetString("Q_2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte zvýšený LDL (“špatný”) cholesterol (rovno nebo vyšší jak 3 mmol/l), a/nebo snížený HDL (“hodný”) cholesterol (méně než 1,2 mmol/l u žen, resp. 1 u mužů)?.
        /// </summary>
        public static string Q_2_7 {
            get {
                return ResourceManager.GetString("Q_2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte zvýšené triacylglyceroly v krvi?  (hodnota vyšší nebo rovna 1,7 mmol/l).
        /// </summary>
        public static string Q_2_8 {
            get {
                return ResourceManager.GetString("Q_2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užíváte léky na vysoký krevní tlak?.
        /// </summary>
        public static string Q_2_9 {
            get {
                return ResourceManager.GetString("Q_2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trpíte častou únavou? (v průběhu dne, ráno po probuzení).
        /// </summary>
        public static string Q_3_1 {
            get {
                return ResourceManager.GetString("Q_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kojíte?.
        /// </summary>
        public static string Q_3_10 {
            get {
                return ResourceManager.GetString("Q_3_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trpíte premenstruačním syndromem? (např. změny nálad, deprese, nafouknuté břicho, nesoustředěnost či bolest hlavy v období mezi ovulací a menstruací).
        /// </summary>
        public static string Q_3_11 {
            get {
                return ResourceManager.GetString("Q_3_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byla jste někdy těhotná?.
        /// </summary>
        public static string Q_3_12 {
            get {
                return ResourceManager.GetString("Q_3_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte/měla jste těhotenskou cukrovku?.
        /// </summary>
        public static string Q_3_13 {
            get {
                return ResourceManager.GetString("Q_3_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plánujete v následujících dvou letech těhotenství?.
        /// </summary>
        public static string Q_3_14 {
            get {
                return ResourceManager.GetString("Q_3_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užíváte hormonální substituci? (např. hormony při menopauze).
        /// </summary>
        public static string Q_3_15 {
            get {
                return ResourceManager.GetString("Q_3_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trpíte návaly nebo jinými příznaky menopauzy?.
        /// </summary>
        public static string Q_3_16 {
            get {
                return ResourceManager.GetString("Q_3_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Létáte často letadlem a/nebo máte dlouhodobé znehybnění? (sádrový obvaz, upoutání na lůžko).
        /// </summary>
        public static string Q_3_17 {
            get {
                return ResourceManager.GetString("Q_3_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kouříte?.
        /// </summary>
        public static string Q_3_18 {
            get {
                return ResourceManager.GetString("Q_3_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trpíte nespavostí či nekvalitním spánkem? (špatné usínání, večerní probouzení, pocit nevyspalosti ráno).
        /// </summary>
        public static string Q_3_2 {
            get {
                return ResourceManager.GetString("Q_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V kolik hodin nejčastěji chodíte spát?.
        /// </summary>
        public static string Q_3_3 {
            get {
                return ResourceManager.GetString("Q_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V kolik hodin nejčastěji vstáváte?.
        /// </summary>
        public static string Q_3_4 {
            get {
                return ResourceManager.GetString("Q_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trpíte průjmy? (normální stolice je nejen pravidelná, ale i pevná a zároveň lehce vytlačitelná, pokud máte denně 3 a více vodnatých stolic hovoříme o průjmu).
        /// </summary>
        public static string Q_3_5 {
            get {
                return ResourceManager.GetString("Q_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trpíte zácpou? (normální stolice je nejen pravidelná, ale i pevná a zároveň lehce vytlačitelná, pokud stolice nejde dobře vytlačit hovoříme o zácpě).
        /// </summary>
        public static string Q_3_6 {
            get {
                return ResourceManager.GetString("Q_3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trpíte jinými zažívacími problémy? (pálení žáhy, bolesti břicha).
        /// </summary>
        public static string Q_3_7 {
            get {
                return ResourceManager.GetString("Q_3_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užíváte hormonální antikoncepci? (pokud ano, napište, prosím, její název a jak dlouho ji užíváte).
        /// </summary>
        public static string Q_3_8 {
            get {
                return ResourceManager.GetString("Q_3_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jste těhotná / v šestinedělí?.
        /// </summary>
        public static string Q_3_9 {
            get {
                return ResourceManager.GetString("Q_3_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měli/mají Vaši rodiče, sourozenci nebo prarodiče cukrovku 2. typu?.
        /// </summary>
        public static string Q_4_1 {
            get {
                return ResourceManager.GetString("Q_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měli/mají Vaši rodiče, sourozenci nebo prarodiče tromboembolickou chorobu?.
        /// </summary>
        public static string Q_4_10 {
            get {
                return ResourceManager.GetString("Q_4_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Léčí se někdo ve Vaší rodině na onemocnění srdce a cév? (onemocněním se myslí i vysoký krevní tlak a cholesterol).
        /// </summary>
        public static string Q_4_11 {
            get {
                return ResourceManager.GetString("Q_4_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyskytuje/vyskytovalo se u Vašich rodičů, sourozenců nebo prarodiče ucpávání cév dolních končetin?.
        /// </summary>
        public static string Q_4_12 {
            get {
                return ResourceManager.GetString("Q_4_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měli/mají Vaši rodiče, sourozenci nebo prarodiče infarkt / mozkovou mrtvici?.
        /// </summary>
        public static string Q_4_2 {
            get {
                return ResourceManager.GetString("Q_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měli/mají Vaši rodiče, sourozenci nebo prarodiče vysoký cholesterol?.
        /// </summary>
        public static string Q_4_3 {
            get {
                return ResourceManager.GetString("Q_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měli/mají Vaši rodiče, sourozenci nebo prarodiče nadváhu nebo obezitu?.
        /// </summary>
        public static string Q_4_4 {
            get {
                return ResourceManager.GetString("Q_4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měli/mají Vaši rodiče, sourozenci nebo prarodiče nádorové onemocnění?.
        /// </summary>
        public static string Q_4_5 {
            get {
                return ResourceManager.GetString("Q_4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měli/mají Vaši rodiče, sourozenci nebo prarodiče nádorové onemocnění prsu/ vaječníků/vejcovodu?.
        /// </summary>
        public static string Q_4_6 {
            get {
                return ResourceManager.GetString("Q_4_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měli/mají Vaši rodiče, sourozenci nebo prarodiče nádorové onemocnění prsu u muže?.
        /// </summary>
        public static string Q_4_7 {
            get {
                return ResourceManager.GetString("Q_4_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byly v rodině častější potraty? (spontánní, nikoliv plánovaná interrupce).
        /// </summary>
        public static string Q_4_8 {
            get {
                return ResourceManager.GetString("Q_4_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byly v rodině předčasné porody? (spontánní, nikoliv plánované lékařem).
        /// </summary>
        public static string Q_4_9 {
            get {
                return ResourceManager.GetString("Q_4_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte diagnostikovanou intoleranci na laktózu (mléčný cukr) nebo alergii na mléko? (ano odpovídejte pouze v případě, že je intolerance/alergie lékařsky diagnostikována).
        /// </summary>
        public static string Q_5_1 {
            get {
                return ResourceManager.GetString("Q_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jste vegan/ka?.
        /// </summary>
        public static string Q_5_10 {
            get {
                return ResourceManager.GetString("Q_5_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jste vegetarián/ka?.
        /// </summary>
        public static string Q_5_11 {
            get {
                return ResourceManager.GetString("Q_5_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jíte běžně minimálně  4x týdně maso?.
        /// </summary>
        public static string Q_5_12 {
            get {
                return ResourceManager.GetString("Q_5_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jíte ryby?.
        /// </summary>
        public static string Q_5_13 {
            get {
                return ResourceManager.GetString("Q_5_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jíte vejce a jídla z nich (např. pomazánku) obvykle více než 1x týdně?.
        /// </summary>
        public static string Q_5_14 {
            get {
                return ResourceManager.GetString("Q_5_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konzumujete mléko, mléčné výrobky (zakysané mléčné výrobky, jogurty, tvarohy,  smetany, sýry) a jídla z nich (např. smetanové omáčky) více než 3x týdně?.
        /// </summary>
        public static string Q_5_15 {
            get {
                return ResourceManager.GetString("Q_5_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte rád/a pálivá (ostrá) jídla?.
        /// </summary>
        public static string Q_5_16 {
            get {
                return ResourceManager.GetString("Q_5_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Míváte nepřekonatelnou chuť na sladké?.
        /// </summary>
        public static string Q_5_17 {
            get {
                return ResourceManager.GetString("Q_5_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypište potraviny, které nejíte/nemají být v jídelníčku zařazené:.
        /// </summary>
        public static string Q_5_18 {
            get {
                return ResourceManager.GetString("Q_5_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezprostředně po konzumaci potravin s mlékem nebo mléka máte zažívací problémy?.
        /// </summary>
        public static string Q_5_2 {
            get {
                return ResourceManager.GetString("Q_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyskytuje se laktózová intolerance ve Vaší rodině? (rodiče, prarodiče, sourozenci).
        /// </summary>
        public static string Q_5_3 {
            get {
                return ResourceManager.GetString("Q_5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte diagnostikovanou intoleranci nebo alergii na lepek? (ano odpovídejte pouze v případě, že je alergie lékařsky diagnostikována).
        /// </summary>
        public static string Q_5_4 {
            get {
                return ResourceManager.GetString("Q_5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezprostředně po konzumaci potravin s lepkem máte zažívací problémy?.
        /// </summary>
        public static string Q_5_5 {
            get {
                return ResourceManager.GetString("Q_5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyskytuje se celiakie ve Vaší rodině? (rodiče, prarodiče, sourozenci).
        /// </summary>
        public static string Q_5_6 {
            get {
                return ResourceManager.GetString("Q_5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte diagnostikovanou histaminovou intoleranci?.
        /// </summary>
        public static string Q_5_7 {
            get {
                return ResourceManager.GetString("Q_5_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud máte intoleranci na jiné potraviny, vypište je, prosím:.
        /// </summary>
        public static string Q_5_8 {
            get {
                return ResourceManager.GetString("Q_5_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud máte alergii na jiné potraviny, vypište je, prosím:.
        /// </summary>
        public static string Q_5_9 {
            get {
                return ResourceManager.GetString("Q_5_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNÍDANĚ: (například “1 silný plátek chleba šumava s tenkou vrstvou másla a plátkem 30% eidamu, 3 kolečka okurky; káva s polotučným mlékem a 1 lžičkou cukru&quot;, &quot;nic&quot;).
        /// </summary>
        public static string Q_6_1 {
            get {
                return ResourceManager.GetString("Q_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napište, prosím, jaké nápoje nejčastěji pijete:  (např. neperlivá voda, ochucené minerálky, džus, coca-cola, čaj).
        /// </summary>
        public static string Q_6_10 {
            get {
                return ResourceManager.GetString("Q_6_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pijete kávu?.
        /// </summary>
        public static string Q_6_11 {
            get {
                return ResourceManager.GetString("Q_6_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak často pijete kávu?.
        /// </summary>
        public static string Q_6_12 {
            get {
                return ResourceManager.GetString("Q_6_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud pijete kávu, popište, prosím, jakou kávu pijete: (např. s 1 lžičkou cukru, s plnotučným mlékem, espresso, turek).
        /// </summary>
        public static string Q_6_13 {
            get {
                return ResourceManager.GetString("Q_6_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doslazujete často nápoje a pokrmy cukrem (min. 3x týdně)?.
        /// </summary>
        public static string Q_6_14 {
            get {
                return ResourceManager.GetString("Q_6_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pijete minimálně 1x týdně sladké a kalorické nealkoholické nápoje? (coca-cola, náhražky coca-coly, džusy,sladké minerální vody, ledové čaje).
        /// </summary>
        public static string Q_6_15 {
            get {
                return ResourceManager.GetString("Q_6_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konzumujete více než 2x týdně alkoholické nápoje ? (pivo, víno, míchané drinky, tvrdý alkohol).
        /// </summary>
        public static string Q_6_16 {
            get {
                return ResourceManager.GetString("Q_6_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte sedavé zaměstnání? (pokud máte zaměstnání, kde se střídá sezení a pohyb, vybírejte podle častější převahy).
        /// </summary>
        public static string Q_6_17 {
            get {
                return ResourceManager.GetString("Q_6_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trávíte často delší dobu v autě na cestách? (často znamená několikrát týdně).
        /// </summary>
        public static string Q_6_18 {
            get {
                return ResourceManager.GetString("Q_6_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pracujete na směny?.
        /// </summary>
        public static string Q_6_19 {
            get {
                return ResourceManager.GetString("Q_6_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOPOLEDNÍ SVAČINA: (například &quot;1 velké jablko a 3 kostičky mléčné čokolády&quot;, &quot;nic&quot;).
        /// </summary>
        public static string Q_6_2 {
            get {
                return ResourceManager.GetString("Q_6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud ano, vyberte způsob střídání směn:.
        /// </summary>
        public static string Q_6_20 {
            get {
                return ResourceManager.GetString("Q_6_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stíháte v zaměstnání pravidelně jíst? (v případě potřeby se můžete najíst).
        /// </summary>
        public static string Q_6_21 {
            get {
                return ResourceManager.GetString("Q_6_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte v zaměstnání možnost ohřát si jídlo?.
        /// </summary>
        public static string Q_6_22 {
            get {
                return ResourceManager.GetString("Q_6_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaříte si a jste schopni si většinu jídel připravovat doma?.
        /// </summary>
        public static string Q_6_23 {
            get {
                return ResourceManager.GetString("Q_6_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stravujete se více jak 2x týdně v restauracích? (včetně závodních jídelen).
        /// </summary>
        public static string Q_6_24 {
            get {
                return ResourceManager.GetString("Q_6_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stravujete se více jak 2 x týdně ve fastfoodu?.
        /// </summary>
        public static string Q_6_25 {
            get {
                return ResourceManager.GetString("Q_6_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konzumujete ve večerních hodinách (min. 1x týdně) nezdravé jídlo? (za nezdravé jídlo ve večerních hodinách můžete považovat obecně nezdravé potraviny, velké množství jídla a také potraviny nebo pokrmy s vysokým obsahem sacharidů nebo příliš velkým množstvím tuku).
        /// </summary>
        public static string Q_6_26 {
            get {
                return ResourceManager.GetString("Q_6_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chodíte rádi pěšky? (jít 15 minut místo použití dopravy mi nedělá problém).
        /// </summary>
        public static string Q_6_27 {
            get {
                return ResourceManager.GetString("Q_6_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak často a jakou pohybovou aktivitu máte?.
        /// </summary>
        public static string Q_6_28 {
            get {
                return ResourceManager.GetString("Q_6_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaké pohybové aktivity preferujete?  (např. běh, cyklistika, plavání, vyberte preferované pohybové aktivity i v případě,  že v současné době aktivně nesportujete).
        /// </summary>
        public static string Q_6_29 {
            get {
                return ResourceManager.GetString("Q_6_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBĚD: (například &quot;čtvrtka pečeného kuřete s kůží, výpek, 2 střední brambory přelité máslem a po obědě 1 malý větrník&quot;, &quot;nic&quot;).
        /// </summary>
        public static string Q_6_3 {
            get {
                return ResourceManager.GetString("Q_6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trpíte omezenou hybností kloubů či bolestí kloubů, která Vás limituje v pohybové aktivitě?.
        /// </summary>
        public static string Q_6_30 {
            get {
                return ResourceManager.GetString("Q_6_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jste často ve stresu?.
        /// </summary>
        public static string Q_6_31 {
            get {
                return ResourceManager.GetString("Q_6_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud jste často ve stresu, co je jeho hlavní příčinou?.
        /// </summary>
        public static string Q_6_32 {
            get {
                return ResourceManager.GetString("Q_6_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zkoušeli jste už různé diety a bez stálého výsledku nebo jste i přibrali?.
        /// </summary>
        public static string Q_6_33 {
            get {
                return ResourceManager.GetString("Q_6_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud jste zkoušeli diety, vypište, prosím, jaké a s jakým výsledkem: (např. ketodieta mi pomohla zhubnou 5 kg, ale po měsíci byly kg zpátky).
        /// </summary>
        public static string Q_6_34 {
            get {
                return ResourceManager.GetString("Q_6_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete mít v jídelníčku snídani?.
        /// </summary>
        public static string Q_6_35 {
            get {
                return ResourceManager.GetString("Q_6_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete mít v jídelníčku dopolední svačinu?.
        /// </summary>
        public static string Q_6_36 {
            get {
                return ResourceManager.GetString("Q_6_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete mít v jídelníčku oběd?.
        /// </summary>
        public static string Q_6_37 {
            get {
                return ResourceManager.GetString("Q_6_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete mít v jídelníčku odpolední svačinu?.
        /// </summary>
        public static string Q_6_38 {
            get {
                return ResourceManager.GetString("Q_6_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete mít v jídelníčku večeři?.
        /// </summary>
        public static string Q_6_39 {
            get {
                return ResourceManager.GetString("Q_6_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODPOLEDNÍ SVAČINA: (například &quot;150g kelímek bílého smetanového jogurt, 1 polévková lžíce marmelády; Latté&quot;, &quot;nic&quot;).
        /// </summary>
        public static string Q_6_4 {
            get {
                return ResourceManager.GetString("Q_6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete mít v jídelníčku druhou večeři?.
        /// </summary>
        public static string Q_6_40 {
            get {
                return ResourceManager.GetString("Q_6_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEČEŘE: (například &quot;1 silný krajíc žitného chleba s tvarohovou pomazánka s pažitkou, 1 vařené vajíčko, půl červené papriky&quot;, &quot;nic&quot;).
        /// </summary>
        public static string Q_6_5 {
            get {
                return ResourceManager.GetString("Q_6_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to II. VEČEŘE: (například &quot;půl bločku sýra a 2 dcl červeného vína&quot;, &quot;nic&quot;).
        /// </summary>
        public static string Q_6_6 {
            get {
                return ResourceManager.GetString("Q_6_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při současném způsobu stravování pociťujete často hlad?.
        /// </summary>
        public static string Q_6_7 {
            get {
                return ResourceManager.GetString("Q_6_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaké denní porce chcete mít v jídelníčku zařazené?.
        /// </summary>
        public static string Q_6_8 {
            get {
                return ResourceManager.GetString("Q_6_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaké množství nealkoholických nápojů denně vypijete.
        /// </summary>
        public static string Q_6_9 {
            get {
                return ResourceManager.GetString("Q_6_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na jakém místě se Vám začíná ukládat tuk jako první?.
        /// </summary>
        public static string Q_7_1 {
            get {
                return ResourceManager.GetString("Q_7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trpíte hypermobilitou kloubů? (zvýšený rozsah kloubní pohyblivosti).
        /// </summary>
        public static string Q_7_10 {
            get {
                return ResourceManager.GetString("Q_7_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete sdělit svému specialistovi ještě něco co v dotazníku nezaznělo a ovlivní to váš výživový plán?.
        /// </summary>
        public static string Q_7_11 {
            get {
                return ResourceManager.GetString("Q_7_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na kterých místech hubnete jako první?.
        /// </summary>
        public static string Q_7_2 {
            get {
                return ResourceManager.GetString("Q_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trápí Vás celulitida na hýždích a nohou?.
        /// </summary>
        public static string Q_7_3 {
            get {
                return ResourceManager.GetString("Q_7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte křeče dolních končetin?.
        /// </summary>
        public static string Q_7_4 {
            get {
                return ResourceManager.GetString("Q_7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte bolesti dolních končetin?(stupnice: 1 = vůbec–10 = často).
        /// </summary>
        public static string Q_7_5 {
            get {
                return ResourceManager.GetString("Q_7_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud jste míru bolesti končetin označil/a mezi 6 - 10, vyberte, prosím, kdy k bolesti dochází..
        /// </summary>
        public static string Q_7_6 {
            get {
                return ResourceManager.GetString("Q_7_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte otoky dolních končetin?.
        /// </summary>
        public static string Q_7_7 {
            get {
                return ResourceManager.GetString("Q_7_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte křečové žíly?.
        /// </summary>
        public static string Q_7_8 {
            get {
                return ResourceManager.GetString("Q_7_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodělal/a jste v minulosti zánět křečových žil?.
        /// </summary>
        public static string Q_7_9 {
            get {
                return ResourceManager.GetString("Q_7_9", resourceCulture);
            }
        }
    }
}
